name: Hugo Dependency Updates
on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday
  workflow_dispatch:

jobs:
  # Update Hugo modules (themes/components)
  update_modules:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Read current Hugo version
        id: hugo-version
        run: |
          . ./.env
          echo "HUGO_VERSION=${HUGO_VERSION}" >> "${GITHUB_OUTPUT}"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '${{ steps.hugo-version.outputs.HUGO_VERSION }}'
          extended: true

      - name: Update modules
        id: update-modules
        run: |
          hugo mod get -u ./...
          hugo mod tidy

          # Check if there are any changes
          if git diff --quiet; then
            echo "changed=false" >> "${GITHUB_OUTPUT}"
          else
            echo "changed=true" >> "${GITHUB_OUTPUT}"
          fi

      - name: Create PR for modules
        if: steps.update-modules.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "update/hugo-modules-${{ github.run_number }}"
          path: .
          commit-message: "chore: update Hugo modules"
          title: "Update Hugo Modules"
          body: |
            This PR updates Hugo modules (themes and components) to their latest versions.

            Please test the site build and review any visual changes.
          committer: "Flatcar Buildbot <buildbot@flatcar-linux.org>"
          author: "Flatcar Buildbot <buildbot@flatcar-linux.org>"

  # Check for new Hugo binary versions
  check_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Get latest Hugo version
        id: hugo
        run: |
          LATEST=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r '.tag_name' | sed 's/^v//')
          # Validate version format (should be like 0.147.0)
          if ! echo "${LATEST}" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "Error: Invalid Hugo version format: ${LATEST}"
            exit 1
          fi
          echo "latest=${LATEST}" >> "${GITHUB_OUTPUT}"

      - name: Read current Hugo version
        id: hugo-version
        run: |
          . ./.env
          echo "current=${HUGO_VERSION}" >> "${GITHUB_OUTPUT}"

      - name: Update Hugo version in .env
        if: steps.hugo-version.outputs.current != steps.hugo.outputs.latest
        run: |
          # Replace the version in .env
          sed -i "s/^HUGO_VERSION=.*/HUGO_VERSION=${{ steps.hugo.outputs.latest }}/" .env

      - name: Create PR for version update
        if: steps.hugo-version.outputs.current != steps.hugo.outputs.latest
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "update/hugo-${{ steps.hugo.outputs.latest }}"
          path: .
          title: "Update Hugo to ${{ steps.hugo.outputs.latest }}"
          body: |
            This PR updates Hugo from ${{ steps.hugo-version.outputs.current }} to ${{ steps.hugo.outputs.latest }}.

            Please review the [Hugo release notes](https://github.com/gohugoio/hugo/releases/tag/v${{ steps.hugo.outputs.latest }}) for any breaking changes.
          commit-message: "chore: update Hugo to ${{ steps.hugo.outputs.latest }}"
          committer: "Flatcar Buildbot <buildbot@flatcar-linux.org>"
          author: "Flatcar Buildbot <buildbot@flatcar-linux.org>"
          signoff: true
